spring:
  application:
    name: event
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/event
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

